[project]
name = "midori-ai-subsystem-manager-2"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "halo>=0.0.31",
    "nicegui>=2.5.0",
]
